<#
.SYNOPSIS
    Start the ClawTeam web board (dashboard) hidden in the background.

.DESCRIPTION
    Runs `clawteam board serve` as an invisible background process and (by default)
    opens the dashboard in your default browser once. Default port 8788 because
    8080 is commonly occupied (e.g. local LLM gateways).

.EXAMPLE
    .\Start-Board.ps1                # serve on 8788 and open the browser
    .\Start-Board.ps1 -Port 9000 -NoBrowser
#>
param(
    [int]$Port = 8788,
    [string]$Team = "",
    [switch]$NoBrowser,
    [switch]$External
)

$ErrorActionPreference = 'Stop'
$Repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$RunDir = Join-Path $Repo '.clawteam-local\run'
$LogDir = Join-Path $Repo '.clawteam-local\logs'
New-Item -ItemType Directory -Force -Path $RunDir, $LogDir | Out-Null

$env:PATH = "$Repo\.venv\Scripts;$HOME\.local\bin;$env:PATH"
$env:CLAWTEAM_BOARD_PORT = "$Port"
$env:CLAWTEAM_BOARD_HOST = if ($External) { '0.0.0.0' } else { '127.0.0.1' }

$board = Join-Path $RunDir 'board.ps1'
@'
# Auto-generated by Start-Board.ps1 - runs hidden.
$ErrorActionPreference = 'Continue'
$Repo = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSCommandPath))
$Log = Join-Path $Repo '.clawteam-local\logs\board.log'
$Port = $env:CLAWTEAM_BOARD_PORT
$HostAddr = if ($env:CLAWTEAM_BOARD_HOST) { $env:CLAWTEAM_BOARD_HOST } else { '127.0.0.1' }
"[$(Get-Date -Format s)] board serve start ${HostAddr}:$Port" | Add-Content -LiteralPath $Log
& clawteam board serve --host $HostAddr --port $Port *>> $Log
'@ | Set-Content -LiteralPath $board -Encoding UTF8

. (Join-Path $PSScriptRoot 'Invoke-Hidden.ps1')
$boardPid = Start-HiddenScript -ScriptPath $board -WorkingDirectory $Repo
Set-Content -LiteralPath (Join-Path $RunDir 'board.pid') -Value $boardPid

# Photo lane: temporary public photo links (self-hosted, cloudflared) ride with
# the board session — idempotent, silent no-op when the tunnel is not configured.
try { & (Join-Path $PSScriptRoot 'Start-PhotoTunnel.ps1') } catch { Write-Warning "photo tunnel: $_" }

if ($External) {
    # Get-NetIPAddress uses a CIM class that is missing/broken on some systems
    # ("Invalid class" 0x41010); fall back to DNS resolution when it fails.
    $lanIp = $null
    try {
        $lanIp = (Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
            Where-Object { $_.InterfaceAlias -notmatch 'Loopback|vEthernet|WSL|Hyper-V' -and $_.IPAddress -notmatch '^169\.254' } |
            Select-Object -First 1).IPAddress
    } catch {
        $lanIp = ([System.Net.Dns]::GetHostAddresses($env:COMPUTERNAME) |
            Where-Object { $_.AddressFamily -eq 'InterNetwork' -and $_.IPAddressToString -notmatch '^169\.254|^127\.|^100\.' } |
            Select-Object -First 1).IPAddressToString
    }
    Write-Host "Board running (hidden PID $boardPid) on $lanIp`:$Port (LAN) and http://127.0.0.1:$Port"
    Write-Host "Phone: open http://${lanIp}:$Port  (needs the firewall rule from Enable-PhoneControl.ps1, or use adb reverse)"
} else {
    Write-Host "Board running (hidden PID $boardPid) at http://127.0.0.1:$Port"
}
if (-not $NoBrowser) {
    Start-Process "http://127.0.0.1:$Port"
}
