<#
.SYNOPSIS
    Launch the 6-lane ClawTeam agentic-se swarm, fully hidden in the background.

.DESCRIPTION
    Generates a hidden supervisor process (CreateNoWindow) that:
      1. runs `clawteam launch agentic-se --team <Team> --goal <Goal>`
      2. stays alive as the console host for the agent subprocesses (so they are
         never killed by console teardown) and writes a heartbeat to the log
      3. exits when a stop file appears (see Stop-Swarm.ps1)
    Also starts the web board (default port 8788; 8080 is typically occupied).

.EXAMPLE
    .\Start-Swarm.ps1 -Goal "Build a full-stack todo app with auth and React frontend"
    .\Start-Swarm.ps1 -Goal "..." -Team "se-swarm-2" -Profile openrouter-claude -NoBoard
#>
param(
    [Parameter(Mandatory = $true)][string]$Goal,
    [string]$Team = "se-swarm",
    [string]$Profile = "openrouter-claude",
    [string]$Template = "agentic-se",
    [switch]$NoBoard,
    [switch]$ExternalBoard,
    [int]$BoardPort = 8788
)

$ErrorActionPreference = 'Stop'
$Repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)   # scripts\windows -> repo root
$Win = Join-Path $Repo 'scripts\windows'
$RunDir = Join-Path $Repo '.clawteam-local\run'
$LogDir = Join-Path $Repo '.clawteam-local\logs'
New-Item -ItemType Directory -Force -Path $RunDir, $LogDir | Out-Null

# Environment for the hidden supervisor and everything it spawns.
$env:PATH = "$Repo\.venv\Scripts;$HOME\.local\bin;$env:PATH"
$env:CLAWTEAM_TEAM_NAME = $Team
$env:CLAWTEAM_GOAL = $Goal          # passed via env: no quoting/escaping hazards
$env:CLAWTEAM_PROFILE = $Profile
$env:CLAWTEAM_TEMPLATE = $Template
$env:CLAWTEAM_BOARD_PORT = "$BoardPort"

# ---- generate the supervisor script --------------------------------------
$supervisor = Join-Path $RunDir "$Team-supervisor.ps1"
@'
# Auto-generated by Start-Swarm.ps1 - runs hidden, hosts the agent console.
$ErrorActionPreference = 'Continue'
$Team = $env:CLAWTEAM_TEAM_NAME
$Goal = $env:CLAWTEAM_GOAL
$Profile = $env:CLAWTEAM_PROFILE
$Repo = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSCommandPath))
$StopFile = Join-Path $Repo ".clawteam-local\run\$Team.stop"
$Log = Join-Path $Repo ".clawteam-local\logs\$Team.log"

"[$(Get-Date -Format s)] supervisor start: team=$Team" | Add-Content -LiteralPath $Log

$launchArgs = @('launch', $env:CLAWTEAM_TEMPLATE, '--team', $Team, '--goal', $Goal)
if ($Profile) { $launchArgs += @('--profile', $Profile) }
& clawteam @launchArgs *>> $Log
"[$(Get-Date -Format s)] launch returned (agents are detached)" | Add-Content -LiteralPath $Log

# Keep this hidden console alive so agent subprocesses keep theirs.
while (-not (Test-Path -LiteralPath $StopFile)) {
    Start-Sleep -Seconds 60
    "[$(Get-Date -Format s)] heartbeat" | Add-Content -LiteralPath $Log
}
Remove-Item -LiteralPath $StopFile -ErrorAction SilentlyContinue
"[$(Get-Date -Format s)] supervisor stop" | Add-Content -LiteralPath $Log
'@ | Set-Content -LiteralPath $supervisor -Encoding UTF8

. (Join-Path $Win 'Invoke-Hidden.ps1')
$supPid = Start-HiddenScript -ScriptPath $supervisor -WorkingDirectory $Repo
Set-Content -LiteralPath (Join-Path $RunDir "$Team-supervisor.pid") -Value $supPid

Write-Host "Swarm launched (hidden supervisor PID $supPid)"
Write-Host "  team      : $Team"
Write-Host "  template  : $Template (6 lanes: plan, agent, debug, ask, archive, prompt-engineer)"
Write-Host "  log       : $(Join-Path $LogDir "$Team.log")"

if (-not $NoBoard) {
    if ($ExternalBoard) {
        & (Join-Path $Win 'Start-Board.ps1') -Port $BoardPort -Team $Team -External
    } else {
        & (Join-Path $Win 'Start-Board.ps1') -Port $BoardPort -Team $Team
    }
}
