<#
.SYNOPSIS
    Start the cloudflared tunnel that exposes temporary public photo links.

.DESCRIPTION
    Runs `cloudflared tunnel run` for the dedicated `clawteam-photos` tunnel
    (hostname photos.miaknuckles.com -> loopback photo host on 18790) as an
    invisible background process. Idempotent: exits silently when the tunnel
    config or credentials are missing (feature not set up), or when the tunnel
    is already running (pid file + live process check).

    The photo host itself lives inside the board process (clawteam board serve);
    this script only maintains the public https route to it.

.EXAMPLE
    .\Start-PhotoTunnel.ps1
#>
param(
    [string]$Cloudflared = "C:\Tools\cloudflared\cloudflared.exe",
    [string]$TunnelConfig = "$HOME\.cloudflared\clawteam-photos.yml"
)

$ErrorActionPreference = 'Stop'
$RunDir = Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) '.clawteam-local\run'
$LogDir = Join-Path (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)) '.clawteam-local\logs'
New-Item -ItemType Directory -Force -Path $RunDir, $LogDir | Out-Null
$PidFile = Join-Path $RunDir 'photo-tunnel.pid'

# Feature not set up on this machine -> silent no-op.
if (-not (Test-Path -LiteralPath $TunnelConfig)) { exit 0 }
if (-not (Test-Path -LiteralPath $Cloudflared)) {
    Write-Warning "cloudflared not found at $Cloudflared - photo tunnel not started"
    exit 0
}

# Already running -> no-op.
if (Test-Path -LiteralPath $PidFile) {
    $existing = Get-Content -LiteralPath $PidFile -ErrorAction SilentlyContinue
    if ($existing -and (Get-Process -Id $existing -ErrorAction SilentlyContinue)) { exit 0 }
}

$runner = Join-Path $RunDir 'photo-tunnel.ps1'
@"
# Auto-generated by Start-PhotoTunnel.ps1 - runs hidden.
`$ErrorActionPreference = 'Continue'
& '$Cloudflared' --config '$TunnelConfig' tunnel run *>> '$LogDir\photo-tunnel.log'
"@ | Set-Content -LiteralPath $runner -Encoding UTF8

. (Join-Path $PSScriptRoot 'Invoke-Hidden.ps1')
$tunnelPid = Start-HiddenScript -ScriptPath $runner -WorkingDirectory $RunDir
Set-Content -LiteralPath $PidFile -Value $tunnelPid
Write-Host "photo tunnel running (hidden PID $tunnelPid) -> https://photos.miaknuckles.com"
